import { z } from 'zod';

export const createAdSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  subtitle: z.string().optional(),
  badge: z.string().optional(),
  backgroundColor: z.string().default('#003d7a'),
  type: z.string().default('connect'),
  cta: z.string().optional(),
  href: z.string().optional(),
  price: z.string().optional(),
  period: z.string().optional(),
  phone: z.string().optional(),
  features: z.any().optional(),
  services: z.any().optional(),
  extras: z.any().optional(),
  imageUrl: z.string().optional(),
  sortOrder: z.number().default(0),
  isActive: z.boolean().default(true),
  heroTitle: z.string().optional(),
  heroSubtitle: z.string().optional(),
  heroSlides: z.any().optional(),
  heroCtaText: z.string().optional(),
  heroCtaLink: z.string().optional(),
  heroQuoteText: z.string().optional(),
  heroQuoteLink: z.string().optional(),
  textColor: z.string().optional(),
  subtitleColor: z.string().optional(),
  descriptionColor: z.string().optional(),
  ctaBgColor: z.string().optional(),
  ctaTextColor: z.string().optional(),
  secondaryBgColor: z.string().optional(),
  secondaryTextColor: z.string().optional(),
  cardBgColor: z.string().optional(),
  cardAccentColor: z.string().optional(),
  cardNameColor: z.string().optional(),
  cardPriceColor: z.string().optional(),
  cardBtnBgColor: z.string().optional(),
  cardBtnTextColor: z.string().optional(),
  cardBorderColor: z.string().optional(),
  eyebrowBgColor: z.string().optional(),
  eyebrowTextColor: z.string().optional(),
  eyebrowBorderColor: z.string().optional(),
  slideBadgeBgColor: z.string().optional(),
  slideBadgeTextColor: z.string().optional(),
  slideBadgeBorderColor: z.string().optional(),
  heroTemplate: z.string().optional(),
});

export const updateAdSchema = z.object({
  title: z.string().min(1, 'Title is required').optional(),
  subtitle: z.string().optional(),
  badge: z.string().optional(),
  backgroundColor: z.string().optional(),
  type: z.string().optional(),
  cta: z.string().optional(),
  href: z.string().optional(),
  price: z.string().optional(),
  period: z.string().optional(),
  phone: z.string().optional(),
  features: z.any().optional(),
  services: z.any().optional(),
  extras: z.any().optional(),
  imageUrl: z.string().optional(),
  sortOrder: z.number().optional(),
  isActive: z.boolean().optional(),
  heroTitle: z.string().optional(),
  heroSubtitle: z.string().optional(),
  heroSlides: z.any().optional(),
  heroCtaText: z.string().optional(),
  heroCtaLink: z.string().optional(),
  heroQuoteText: z.string().optional(),
  heroQuoteLink: z.string().optional(),
  textColor: z.string().optional(),
  subtitleColor: z.string().optional(),
  descriptionColor: z.string().optional(),
  ctaBgColor: z.string().optional(),
  ctaTextColor: z.string().optional(),
  secondaryBgColor: z.string().optional(),
  secondaryTextColor: z.string().optional(),
  cardBgColor: z.string().optional(),
  cardAccentColor: z.string().optional(),
  cardNameColor: z.string().optional(),
  cardPriceColor: z.string().optional(),
  cardBtnBgColor: z.string().optional(),
  cardBtnTextColor: z.string().optional(),
  cardBorderColor: z.string().optional(),
  eyebrowBgColor: z.string().optional(),
  eyebrowTextColor: z.string().optional(),
  eyebrowBorderColor: z.string().optional(),
  slideBadgeBgColor: z.string().optional(),
  slideBadgeTextColor: z.string().optional(),
  slideBadgeBorderColor: z.string().optional(),
  heroTemplate: z.string().optional(),
});

export const listAdsSchema = z.object({
  page: z.number().optional(),
  limit: z.number().optional(),
  isActive: z.boolean().optional(),
}).passthrough();

export type CreateAdDto = z.infer<typeof createAdSchema>;
export type UpdateAdDto = z.infer<typeof updateAdSchema>;
export type ListAdsDto = z.infer<typeof listAdsSchema>;
